//! TinyOS — Phase 1 kernel entry (PROVIDED, do not modify).
//!
//! Flow:
//!   1. `_start` (entry.asm) sets `sp` and jumps here.
//!   2. We zero .bss, greet the user, call `trap::init()` to install stvec.
//!   3. We load the single batch app (user/hello.bin packed into the kernel)
//!      into `APP_BASE_ADDRESS`, build its initial TrapContext on the kernel
//!      stack, then drop into U-mode through `__restore`.

#![no_std]
#![no_main]
#![feature(panic_info_message)]

#[macro_use]
mod console;
mod sbi;
mod lang_items;
mod types;

mod trap;
mod syscall;
mod loader;
mod batch;

use core::arch::global_asm;

global_asm!(include_str!("entry.asm"));
global_asm!(include_str!("trap/trap.S"));
// `link_app.S` is generated by `build.rs` in a real project; for the lab we
// hard-wire a single embedded app via `loader::LINKED_APP`.

fn clear_bss() {
    extern "C" {
        fn sbss();
        fn ebss();
    }
    unsafe {
        core::slice::from_raw_parts_mut(sbss as usize as *mut u8, ebss as usize - sbss as usize)
            .fill(0);
    }
}

#[no_mangle]
pub extern "C" fn rust_main() -> ! {
    clear_bss();
    println!("[kernel] TinyOS Phase 1 · Traps & Syscalls");
    trap::init();
    batch::run_first_app()
}
