//! main.rs — PROVIDED. Kernel entry for Phase 2.
//!
//! Boot sequence:
//!   1. `_start` (entry.asm) sets sp and jumps here.
//!   2. Zero .bss, init trap vector.
//!   3. Load user apps into their runtime memory.
//!   4. Enable S-mode timer interrupt and arm the first tick.
//!   5. `task::run_first_task()` — __switch into task 0, never returns.

#![no_std]
#![no_main]
#![feature(panic_info_message)]

use core::arch::global_asm;

#[macro_use]
pub mod console;
mod config;
mod lang_items;
mod loader;
mod sbi;
mod syscall;
mod task;
pub mod timer;
mod trap;
pub mod types;

global_asm!(include_str!("entry.asm"));
// `link_app.S` would be generated by a build.rs in a full build; for the lab
// we ship a placeholder that declares a zero-app table so the kernel still
// links. Students will replace it once `user/` is built.
global_asm!(r#"
    .section .data
    .globl _num_app
    .align 3
_num_app:
    .quad 0
    .quad 0
"#);

fn clear_bss() {
    extern "C" { fn sbss(); fn ebss(); }
    unsafe {
        core::slice::from_raw_parts_mut(sbss as usize as *mut u8, ebss as usize - sbss as usize).fill(0);
    }
}

#[no_mangle]
pub fn rust_main() -> ! {
    clear_bss();
    println!("[kernel] TinyOS Phase 2 booting");
    trap::init();
    loader::load_apps();
    trap::enable_timer_interrupt();
    timer::set_next_trigger();
    task::run_first_task();
}
